#!/bin/bash
set -e
declare -A osInfo;
osInfo[/etc/debian_version]="sudo apt-get update && sudo apt-get install -y"
osInfo[/etc/alpine-release]="sudo apk --update add"
osInfo[/etc/centos-release]="sudo yum install -y"
osInfo[/etc/fedora-release]="sudo dnf install -y"
osInfo[/etc/system-release]="sudo yum install -y" #amazon linux

for f in ${!osInfo[@]}
do
  if [[ -f $f ]];then
    package_manager=${osInfo[$f]}
    echo $package_manager
  fi
done

if ! aws --v; then
  eval "$package_manager jq python3 python3-pip"
  pip3 install awscli --upgrade --user
  export PATH=~/.local/bin:$PATH
fi

# get user/key pairs from AWS
secret=$(aws secretsmanager get-secret-value --secret-id users_with_keys_testing)

echo "Pulling keys locally"
while IFS="=" read -r key value; do
  user_name=$key
  user_key=$value
  echo "Pulling key for $user_name"
  if [ -z "$(getent passwd $user_name)" ]; then
    echo "Creating new user $user_name"
    sudo useradd -m $user_name -s /bin/bash
    echo $user_name:password | sudo chpasswd
    sudo su - $user_name -c 'mkdir -p .ssh'
    sudo su - $user_name -c 'chmod 700 .ssh/'
    sudo su - $user_name -c "echo ${user_key} >> .ssh/authorized_keys"
    sudo su - $user_name -c 'chmod 600 .ssh/authorized_keys'

    if grep -q sudo /etc/group; then
      sudo usermod -a -G sudo $user_name
    else
      if grep -q wheel /etc/group; then
        sudo usermod -a -G wheel $user_name
      fi
    fi

    echo "$user_name    ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers.d/whitehat_users #DO NOT CHANGE THIS! if this goes wrong you brick the box
    sudo chage -d 0 $user_name
  fi
done < <(jq -r ".SecretString | fromjson | to_entries|map(\"\(.key)=\(.value)\")|.[]" <<< "$secret")

echo "Finished pulling keys"
